apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  template:
    spec:
      containers:
      - name: pre-install-oai-job
        image: cosmintitei/bash-curl
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "/opt/scripts/precheck.sh"]
        volumeMounts:
          - name: config-volume
            mountPath: /opt/scripts
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-preinstall-configmap
            defaultMode: 0777
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      ttlSecondsAfterFinished: 60
